version: '3'
services:
  nginx:
    image: nginx:1.17.3-alpine
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/html:/etc/nginx/html
      - ./nginx/vhost:/etc/nginx/vhost
      - ./nginx/rewrite:/etc/nginx/rewrite
      - ./certificate:/etc/nginx/certificate
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./logs/nginx:/var/log/nginx
      - ./app:/var/www
      - ./php/sock:/sock
    networks:
      - app
  mysql:
    image: mariadb:10.4.7
    environment:
      - MYSQL_ROOT_PASSWORD=wt123456
    ports:
      - 33060:33060
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sock:/var/run/mysqld
    networks:
      - app
  redis:
    image: redis:5.0.5-alpine
    command: --requirepass "xhb2025top"
    ports:
      - 63790:6379
    volumes:
      - ./redis/data:/data
    networks:
      - app
  rabbitmq:
    image: rabbitmq:3.9.11-management
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app
  elasticsearch:
    build: ./elasticsearch/analysis-ik
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - TZ=Asia/Shanghai
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml
      - ./elasticsearch/config/analysis-ik/custom:/usr/share/elasticsearch/config/analysis-ik/custom
    networks:
      - app
  logstash:
    image: logstash:7.6.1
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
    networks:
      - app
  kibana:
    image: kibana:7.6.1
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      I18N_LOCALE: zh-CN
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - app
  mongo:
    image: mongo:4.2.5
    environment:
      - TZ=Asia/Shanghai
      - wiredTigerCacheSizeGB=1 # 缓存大小配置为使用 1GB
    volumes:
      - ./mongo/db:/data/db #数据文件挂载
      - ./mongo/logs:/data/logs
      - ./mongo/backup:/backup
      - /etc/localtime:/etc/localtime
    ports:
      - 27017:27017
    # --auth 开启权限认证       --noauth 关闭权限认证，找回密码时使用此配置重启服务
    command: mongod --auth
    networks:
      - app
  nacos-registry:
    image: nacos/nacos-server:v2.1.0
    environment:
      - "MODE=standalone"
    ports:
      - 8848:8848
    networks:
      - app
networks:
  app:
